name: Publish binaries to GH

on:
  release:
    types: [ published ]

jobs:
  publish:
    strategy:
      matrix:
        go-version: [ 1.16.x ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Make Release
        run: make release
      - name: Upload release binaries
        uses: alexellis/upload-assets@0.3.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["./dist/redis-benchmark-go_*"]'
